// invocations.rs

pub const OSAMODAS_SUMMONS: &[&str] = &[
    "Wapin",
    "Tofu",
    "Boufette",
    "Arakne",
    "Piou Rouge",
    "Moogrr",
    "Craqueleur Ancestral",
    "Grokoko",
    "Kaskargo",
    "Corbac",
    "Muloune",
    "Long Brick",
    "Chafer Elite",
    "Chuchoteur Porte-Etendard",
    "Mulmouth Enragé",
    "Zespadon",
    "Gros Smare",
    "Abraknyde Ancestral",
    "Cêpolourpode Ecrasant",
    "Sramva",
    "Tiwallieuw Wabbit",
    "Lairdavan",
    "Patapattes",
    "Gerbouille",
    "Phéromane",
    "Dragoeuf Guerrier",
    "Gentibourg",
    "Slek",
    "Loupin",
    "Pinsulaire",
    "Inanite",
    "CeEvroaint",
    "Patafouin",
    "Krakatou",
    "Chimère Veilleuse",
    "Rhinocéroc",
];
